# Generated by Django 2.2.18 on 2021-02-02 10:43

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='props',
            field=django.contrib.postgres.fields.jsonb.JSONField(default=dict),
        ),
    ]
