language: python

python:
  - 3.7

addons:
  apt:
    sources:
    - debian-sid

services:
  - postgresql

install:
  - pip install -r requirements.txt
  - pip install pylint pylint-django

script:
  # By default max-line-length is 100, but specify it explicitly.
  - find -name "*.py" -not -path "./.git/*" -not -path "*/migrations/*" ! -name "tests.py" | xargs pylint --max-line-length=100 --load-plugins=pylint_django --disable=imported-auth-user
  # Lint the test modules in a different way -- ignore
  # missing-function-docstring since each test case name is self-descriptive,
  # so there is no need to repeat them in docstrings.
  - find . -name tests.py | xargs pylint --max-line-length=100 --load-plugins=pylint_django --disable=missing-function-docstring,imported-auth-user
  - env PG_PORT=5432 SECRET_KEY=secret python3 manage.py test
