language: python

python:
  - 3.7

addons:
  apt:
    sources:
    - debian-sid

install:
  - pip install -r requirements.txt
  - pip install pylint pylint-django

script:
  # By default max-line-length is 100, but specify it explicitly.
  - find -name "*.py" -not -path "./.git/*" -not -path "*/migrations/*" ! -name "tests.py" | xargs pylint --max-line-length=100 --load-plugins=pylint_django
