# Generated by Django 2.1.7 on 2019-02-24 10:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BuildType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='BuildTypeName',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
            ],
        ),
        migrations.CreateModel(
            name='CodeName',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('generation', models.CharField(blank=True, max_length=32)),
                ('model', models.CharField(max_length=255)),
                ('active', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='DeviceName',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
            ],
        ),
        migrations.CreateModel(
            name='DistroName',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='images.Device')),
            ],
        ),
        migrations.CreateModel(
            name='OS',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.CharField(max_length=32)),
                ('active', models.BooleanField(default=False)),
                ('codename', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='images.CodeName')),
                ('name', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='images.DistroName')),
            ],
        ),
        migrations.CreateModel(
            name='Port',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
            ],
        ),
        migrations.AddField(
            model_name='os',
            name='port',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='images.Port'),
        ),
        migrations.AddField(
            model_name='image',
            name='os',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='images.OS'),
        ),
        migrations.AddField(
            model_name='device',
            name='name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='images.DeviceName'),
        ),
        migrations.AddField(
            model_name='device',
            name='supported_os',
            field=models.ManyToManyField(to='images.OS'),
        ),
        migrations.AddField(
            model_name='buildtype',
            name='build_type',
            field=models.ManyToManyField(to='images.BuildTypeName'),
        ),
        migrations.AddField(
            model_name='buildtype',
            name='device',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='images.Device'),
        ),
        migrations.AddField(
            model_name='buildtype',
            name='os',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='images.OS'),
        ),
    ]
