# Generated by Django 2.2.16 on 2020-10-24 09:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BuildTypeName',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
            ],
        ),
        migrations.CreateModel(
            name='CodeName',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='DeviceName',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
            ],
        ),
        migrations.CreateModel(
            name='DistroName',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Port',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
            ],
        ),
        migrations.CreateModel(
            name='OS',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.CharField(max_length=32)),
                ('packages_url', models.CharField(blank=True, max_length=64)),
                ('active', models.BooleanField(default=False)),
                ('codename', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='images.CodeName')),
                ('name', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='images.DistroName')),
                ('port', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='images.Port')),
            ],
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_id', models.CharField(max_length=36)),
                ('device_name', models.CharField(max_length=64)),
                ('distro_name', models.CharField(max_length=64)),
                ('flavour', models.CharField(choices=[('M', 'Mender'), ('C', 'Classic'), ('A', 'Artifact')], default='C', max_length=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('U', 'Undefined'), ('P', 'Pending'), ('B', 'Building'), ('F', 'Failed'), ('S', 'Succeeded')], default='U', max_length=1)),
                ('notes', models.TextField(default='')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('generation', models.CharField(blank=True, max_length=32)),
                ('model', models.CharField(max_length=255)),
                ('active', models.BooleanField(default=False)),
                ('name', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='images.DeviceName')),
                ('supported_os', models.ManyToManyField(to='images.OS')),
            ],
        ),
        migrations.CreateModel(
            name='BuildType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('build_type', models.ManyToManyField(to='images.BuildTypeName')),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='images.Device')),
                ('os', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='images.OS')),
            ],
            options={
                'unique_together': {('device', 'os')},
            },
        ),
    ]
