# Generated by Django 2.1.7 on 2019-03-08 13:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='buildtype',
            unique_together={('device', 'os')},
        ),
    ]
