# Generated by Django 2.2.16 on 2020-11-08 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='build_log',
            field=models.TextField(default=''),
        ),
    ]
