# Generated by Django 2.2.16 on 2020-11-10 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0002_image_build_log'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='flavour',
            field=models.CharField(choices=[('A', 'Artifact'), ('C', 'Classic'), ('M', 'Mender')], default='C', max_length=1),
        ),
        migrations.AlterField(
            model_name='image',
            name='status',
            field=models.CharField(choices=[('U', 'Undefined'), ('P', 'Pending'), ('B', 'Building'), ('F', 'Failed'), ('I', 'Interrupted'), ('S', 'Succeeded')], default='U', max_length=1),
        ),
    ]
