# Generated by Django 2.2.17 on 2021-02-09 09:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0003_auto_20201110_1702'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='device',
            name='name',
        ),
        migrations.RemoveField(
            model_name='device',
            name='supported_os',
        ),
        migrations.RemoveField(
            model_name='os',
            name='codename',
        ),
        migrations.RemoveField(
            model_name='os',
            name='name',
        ),
        migrations.RemoveField(
            model_name='os',
            name='port',
        ),
        migrations.DeleteModel(
            name='BuildType',
        ),
        migrations.DeleteModel(
            name='BuildTypeName',
        ),
        migrations.DeleteModel(
            name='CodeName',
        ),
        migrations.DeleteModel(
            name='Device',
        ),
        migrations.DeleteModel(
            name='DeviceName',
        ),
        migrations.DeleteModel(
            name='DistroName',
        ),
        migrations.DeleteModel(
            name='OS',
        ),
        migrations.DeleteModel(
            name='Port',
        ),
    ]
