# Generated by Django 2.2.12 on 2020-05-29 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0004_auto_20200322_1053'),
    ]

    operations = [
        migrations.AddField(
            model_name='os',
            name='packages_url',
            field=models.CharField(blank=True, max_length=64),
        ),
    ]
