# Generated by Django 2.2.17 on 2021-02-25 15:03

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0004_auto_20210209_0936'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='props',
            field=django.contrib.postgres.fields.jsonb.JSONField(default=dict),
        ),
    ]
